### ISSUE TITLE
User model missing a boolean field status

### ISSUE THREAD

**Issue by ethicalrushi** [ECellNitrr/EcellWeb2k19#3]
User model requires a boolean field status to show that user is verified. Turning default 'is_active' parameter false will suspend the account, we can instead use status to allow only verified users access to certain content.

**Comment by r-tron18** [comment]
> User model requires a boolean field status to show that user is verified. Turning default 'is_active' parameter false will suspend the account, we can instead use status to allow only verified users access to certain content.

Cant we use LoginRequiredMixin
or login_required decorator
